---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ibge

ibge is a work in progress. The idea is to download and make available (in a tidy format) the data from the IBGE [Cidades](https://cidades.ibge.gov.br/) project. 

As this is A WIP, contributions are welcome. GET requests for this are quite straightforward. 

Proof of concept:

```{r}

library(dplyr) # pipe

x <- httr::GET("https://servicodados.ibge.gov.br/api/v1/biblioteca?aspas=3&codmun=280030") %>% 
  xml2::read_html() %>% 
  rvest::html_text() %>% 
  jsonlite::fromJSON()

library(purrr)

df <- tibble(
  municipio = map_chr(x, "MUNICIPIO", .null = NA_character_), 
  estado = map_chr(x, "ESTADO", .null = NA_character_),
  history = map_chr(x, "HISTORICO", .null = NA_character_),
  source_history = map_chr(x, "HISTORICO_FONTE", .null = NA_character_),
  administrative_history = map_chr(x, "FORMACAO_ADMINISTRATIVA", .null = NA_character_),
  locals = map_chr(x, "GENTILICO", .null = NA_character_)
  ) %>% 
  tidyr::separate(estado, into = c("state", "uf"), sep = " - ")

df
```

There is a dataset of municipio codes, names and UFs included. 

```{r}
data("ibge_codes")
head(ibge_codes)
```
